name: Copy Contents

on:
    workflow_call:
        inputs:
            build-type:
                required: true
                type: string

concurrency:
    group: copy-contents-build-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-lighting-app-copy:
        name: Build Lighting App (Copy Contents)
        uses: ./.github/workflows/copy-contents-platform-builder.yaml
        with:
            example-app: "lighting-app"
            build-type: ${{ inputs.build-type }}
            efr32-thread-support: true
            siwx917-soc-support: true

    build-thermostat-copy:
        name: Build Thermostat (Copy Contents)
        uses: ./.github/workflows/copy-contents-platform-builder.yaml
        with:
            example-app: "thermostat"
            build-type: ${{ inputs.build-type }}
            efr32-rs911x-support: true
            siwx917-soc-support: true

    build-lock-app-copy:
        name: Build Lock App (Copy Contents)
        uses: ./.github/workflows/copy-contents-platform-builder.yaml
        with:
            example-app: "lock-app"
            build-type: ${{ inputs.build-type }}
            efr32-wf200-support: true
            siwx917-soc-support: true

    build-window-app-copy:
        name: Build Window App (Copy Contents)
        uses: ./.github/workflows/copy-contents-platform-builder.yaml
        with:
            example-app: "window-app"
            build-type: ${{ inputs.build-type }}
            efr32-917ncp-support: true
            siwx917-soc-support: true

    build-zigbee-matter-light-copy:
        name: Build Zigbee Matter Light (Copy Contents)
        uses: ./.github/workflows/copy-contents-platform-builder.yaml
        with:
            example-app: "zigbee-matter-light"
            build-type: ${{ inputs.build-type }}
            efr32-thread-support: true

    # Additional apps for full build
    build-light-switch-app-copy:
        if: ${{ inputs.build-type == 'full' }}
        name: Build Light Switch App (Copy Contents)
        uses: ./.github/workflows/copy-contents-platform-builder.yaml
        with:
            example-app: "light-switch-app"
            build-type: ${{ inputs.build-type }}
            efr32-thread-support: true
            siwx917-soc-support: true

    build-onoff-plug-app-copy:
        if: ${{ inputs.build-type == 'full' }}
        name: Build OnOff Plug App (Copy Contents)
        uses: ./.github/workflows/copy-contents-platform-builder.yaml
        with:
            example-app: "onoff-plug-app"
            build-type: ${{ inputs.build-type }}
            efr32-thread-support: true
            siwx917-soc-support: true

    build-multi-sensor-app-copy:
        if: ${{ inputs.build-type == 'full' }}
        name: Build Multi Sensor App (Copy Contents)
        uses: ./.github/workflows/copy-contents-platform-builder.yaml
        with:
            example-app: "multi-sensor-app"
            build-type: ${{ inputs.build-type }}
            efr32-thread-support: true
            siwx917-soc-support: true

    build-air-quality-sensor-app-copy:
        if: ${{ inputs.build-type == 'full' }}
        name: Build Air Quality Sensor App (Copy Contents)
        uses: ./.github/workflows/copy-contents-platform-builder.yaml
        with:
            example-app: "air-quality-sensor-app"
            build-type: ${{ inputs.build-type }}
            efr32-thread-support: true
            siwx917-soc-support: true

    build-refrigerator-app-copy:
        if: ${{ inputs.build-type == 'full' }}
        name: Build Refrigerator App (Copy Contents)
        uses: ./.github/workflows/copy-contents-platform-builder.yaml
        with:
            example-app: "refrigerator-app"
            build-type: ${{ inputs.build-type }}
            efr32-thread-support: true
            siwx917-soc-support: true

    build-fan-control-app-copy:
        name: Build Fan Control App (Copy Contents)
        uses: ./.github/workflows/copy-contents-platform-builder.yaml
        with:
            example-app: "fan-control-app"
            build-type: ${{ inputs.build-type }}
            siwx917-soc-support: true


